name: iOS Tests and Coverage

on:
  push:
    branches:
      - "**"

  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: ./EATSIT

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select stable Xcode 16
        run: sudo xcode-select -s /Applications/Xcode_16.0.app/Contents/Developer

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Run Unit + UI Tests with Coverage
        run: |
          xcodebuild \
            -project EATSIT.xcodeproj \
            -scheme EATSIT \
            -destination "platform=iOS Simulator,name=iPhone SE (3rd generation),OS=17.5" \
            -enableCodeCoverage YES \
            clean test

      - name: Create coverage folder
        run: mkdir -p coverage

      - name: Export coverage report
        run: |
          RESULT_BUNDLE=$(find ~/Library/Developer/Xcode/DerivedData -name "*.xcresult" | head -1)
          echo "Using result bundle:"
          echo $RESULT_BUNDLE
          xcrun xccov view --report "$RESULT_BUNDLE" > coverage/coverage-report.txt

      - name: Show coverage report
        run: cat coverage/coverage-report.txt

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: EATSIT/coverage/

      - name: Upload xcresult bundle
        uses: actions/upload-artifact@v4
        with:
          name: xcresult
          path: ~/Library/Developer/Xcode/DerivedData
